-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 20:42:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`loko_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loko_type` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`loko_type` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`loko_pads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loko_pads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pads` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`loko_pads` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`loko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loko` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `series` VARCHAR(45) NOT NULL,
  `pads` INT NULL DEFAULT 0,
  `type` INT NULL,
  `axles` INT UNSIGNED NOT NULL DEFAULT 6,
  `weight` FLOAT UNSIGNED NOT NULL DEFAULT 100,
  `force` FLOAT UNSIGNED NOT NULL DEFAULT 5,
  `desc` VARCHAR(60) NULL,
  `URL` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_pads`
    FOREIGN KEY (`pads`)
    REFERENCES `mydb`.`loko_pads` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_type`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`loko_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`loko` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `series_UNIQUE` ON `mydb`.`loko` (`series` ASC) VISIBLE;

CREATE INDEX `id_pads_idx` ON `mydb`.`loko` (`pads` ASC) VISIBLE;

CREATE INDEX `id_type_idx` ON `mydb`.`loko` (`type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`vagon_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vagon_type` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `type_vag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`vagon_type` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`vagon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vagon` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `name` VARCHAR(45) NOT NULL,
  `force` FLOAT NOT NULL,
  `vag_type` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_type`
    FOREIGN KEY (`vag_type`)
    REFERENCES `mydb`.`vagon_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `mydb`.`vagon` (`id` ASC) VISIBLE;

CREATE INDEX `id_type_idx` ON `mydb`.`vagon` (`vag_type` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
